---
- name: Install and configure NGINX on Amazon Linux
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Replace default index.html
      copy:
        content: "<h1>Hello from Terraform + Ansible (Amazon Linux)</h1>"
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
