

- name: Nginx and Ansible
  hosts: all
  become: yes
  gather_facts: false

  vars:
    ansible_become_method: sudo
    ansible_become_user: root
    ansible_become_flags: "-H -n"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Python 3
      raw: sudo dnf install -y python3

    - name: Install pip
      raw: sudo dnf install -y python3-pip

    - name: install boto3
      pip:
        name: boto3
        state: present

    - name: install botocore
      pip:
        name: botocore
        state: present

    - name: Install NGINX
      dnf:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Replace default index.html
      copy:
        content: "<h1>Terraform + Ansible</h1>"
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
