---
- name: Nginx and Ansible
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install Python
      yum:
        name: python3
        state: present

    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Replace default index.html
      copy:
        content: "<h1>Terraform + Ansible</h1>"
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
